// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'api.dart';
import 'api/account_groups.dart';
import 'api/accounts.dart';
import 'api/bug_report.dart';
import 'api/chat_list.dart';
import 'api/drafts.dart';
import 'api/error.dart';
import 'api/groups.dart';
import 'api/logs.dart';
import 'api/media_files.dart';
import 'api/messages.dart';
import 'api/metadata.dart';
import 'api/notifications.dart';
import 'api/relays.dart';
import 'api/signer.dart';
import 'api/user_search.dart';
import 'api/users.dart';
import 'api/utils.dart';
import 'api/zapstore.dart';
import 'frb_generated.dart';
import 'lib.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppSettingsPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettingsPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DartSignerPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSignerPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GroupIdPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupIdPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LanguagePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguagePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PublicKeyPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKeyPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RelayTypePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayTypePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RelayUrlPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrlPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TagPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTagPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ThemeModePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeModePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AppSettings
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    dynamic raw,
  );

  @protected
  DartSigner
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    dynamic raw,
  );

  @protected
  GroupId
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    dynamic raw,
  );

  @protected
  Language
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    dynamic raw,
  );

  @protected
  PublicKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    dynamic raw,
  );

  @protected
  RelayType
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    dynamic raw,
  );

  @protected
  RelayUrl
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    dynamic raw,
  );

  @protected
  Tag
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    dynamic raw,
  );

  @protected
  ThemeMode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    dynamic raw,
  );

  @protected
  AppSettings
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    dynamic raw,
  );

  @protected
  GroupId
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    dynamic raw,
  );

  @protected
  Language
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    dynamic raw,
  );

  @protected
  RelayUrl
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    dynamic raw,
  );

  @protected
  ThemeMode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    dynamic raw,
  );

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  FutureOr<String> Function(String)
  dco_decode_DartFn_Inputs_String_Output_String_AnyhowException(dynamic raw);

  @protected
  FutureOr<String> Function(String, String)
  dco_decode_DartFn_Inputs_String_String_Output_String_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  AppSettings
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    dynamic raw,
  );

  @protected
  DartSigner
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    dynamic raw,
  );

  @protected
  GroupId
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    dynamic raw,
  );

  @protected
  Language
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    dynamic raw,
  );

  @protected
  PublicKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    dynamic raw,
  );

  @protected
  RelayType
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    dynamic raw,
  );

  @protected
  RelayUrl
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    dynamic raw,
  );

  @protected
  Tag
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    dynamic raw,
  );

  @protected
  ThemeMode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<ChatListStreamItem>
  dco_decode_StreamSink_chat_list_stream_item_Sse(dynamic raw);

  @protected
  RustStreamSink<MessageStreamItem>
  dco_decode_StreamSink_message_stream_item_Sse(dynamic raw);

  @protected
  RustStreamSink<NotificationUpdate>
  dco_decode_StreamSink_notification_update_Sse(dynamic raw);

  @protected
  RustStreamSink<UserSearchUpdate> dco_decode_StreamSink_user_search_update_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<UserStreamItem> dco_decode_StreamSink_user_stream_item_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Account dco_decode_account(dynamic raw);

  @protected
  AccountGroup dco_decode_account_group(dynamic raw);

  @protected
  AccountType dco_decode_account_type(dynamic raw);

  @protected
  ApiError dco_decode_api_error(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  ApiError dco_decode_box_autoadd_api_error(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ChatListUpdate dco_decode_box_autoadd_chat_list_update(dynamic raw);

  @protected
  ChatMessageSummary dco_decode_box_autoadd_chat_message_summary(dynamic raw);

  @protected
  DeliveryStatus dco_decode_box_autoadd_delivery_status(dynamic raw);

  @protected
  Draft dco_decode_box_autoadd_draft(dynamic raw);

  @protected
  FileMetadata dco_decode_box_autoadd_file_metadata(dynamic raw);

  @protected
  FlutterEvent dco_decode_box_autoadd_flutter_event(dynamic raw);

  @protected
  FlutterGroupDataUpdate dco_decode_box_autoadd_flutter_group_data_update(
    dynamic raw,
  );

  @protected
  FlutterMetadata dco_decode_box_autoadd_flutter_metadata(dynamic raw);

  @protected
  Group dco_decode_box_autoadd_group(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MessageUpdate dco_decode_box_autoadd_message_update(dynamic raw);

  @protected
  User dco_decode_box_autoadd_user(dynamic raw);

  @protected
  UserUpdate dco_decode_box_autoadd_user_update(dynamic raw);

  @protected
  WhitenoiseConfig dco_decode_box_autoadd_whitenoise_config(dynamic raw);

  @protected
  ChatListStreamItem dco_decode_chat_list_stream_item(dynamic raw);

  @protected
  ChatListUpdate dco_decode_chat_list_update(dynamic raw);

  @protected
  ChatListUpdateTrigger dco_decode_chat_list_update_trigger(dynamic raw);

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw);

  @protected
  ChatMessageSummary dco_decode_chat_message_summary(dynamic raw);

  @protected
  ChatSummary dco_decode_chat_summary(dynamic raw);

  @protected
  DeliveryStatus dco_decode_delivery_status(dynamic raw);

  @protected
  Draft dco_decode_draft(dynamic raw);

  @protected
  EmojiReaction dco_decode_emoji_reaction(dynamic raw);

  @protected
  FileMetadata dco_decode_file_metadata(dynamic raw);

  @protected
  FlutterEvent dco_decode_flutter_event(dynamic raw);

  @protected
  FlutterGroupDataUpdate dco_decode_flutter_group_data_update(dynamic raw);

  @protected
  FlutterMetadata dco_decode_flutter_metadata(dynamic raw);

  @protected
  Group dco_decode_group(dynamic raw);

  @protected
  GroupInformation dco_decode_group_information(dynamic raw);

  @protected
  GroupState dco_decode_group_state(dynamic raw);

  @protected
  GroupType dco_decode_group_type(dynamic raw);

  @protected
  GroupWithInfoAndMembership dco_decode_group_with_info_and_membership(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  KeyPackageStatus dco_decode_key_package_status(dynamic raw);

  @protected
  LeafNodeInfo dco_decode_leaf_node_info(dynamic raw);

  @protected
  List<Tag>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Account> dco_decode_list_account(dynamic raw);

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw);

  @protected
  List<ChatSummary> dco_decode_list_chat_summary(dynamic raw);

  @protected
  List<EmojiReaction> dco_decode_list_emoji_reaction(dynamic raw);

  @protected
  List<FlutterEvent> dco_decode_list_flutter_event(dynamic raw);

  @protected
  List<Group> dco_decode_list_group(dynamic raw);

  @protected
  List<GroupInformation> dco_decode_list_group_information(dynamic raw);

  @protected
  List<GroupWithInfoAndMembership>
  dco_decode_list_group_with_info_and_membership(dynamic raw);

  @protected
  List<LeafNodeInfo> dco_decode_list_leaf_node_info(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<MatchedField> dco_decode_list_matched_field(dynamic raw);

  @protected
  List<MediaFile> dco_decode_list_media_file(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<Relay> dco_decode_list_relay(dynamic raw);

  @protected
  List<SerializableToken> dco_decode_list_serializable_token(dynamic raw);

  @protected
  List<User> dco_decode_list_user(dynamic raw);

  @protected
  List<UserReaction> dco_decode_list_user_reaction(dynamic raw);

  @protected
  List<UserSearchResult> dco_decode_list_user_search_result(dynamic raw);

  @protected
  LoginResult dco_decode_login_result(dynamic raw);

  @protected
  LoginStatus dco_decode_login_status(dynamic raw);

  @protected
  MatchQuality dco_decode_match_quality(dynamic raw);

  @protected
  MatchedField dco_decode_matched_field(dynamic raw);

  @protected
  MediaFile dco_decode_media_file(dynamic raw);

  @protected
  MessageStreamItem dco_decode_message_stream_item(dynamic raw);

  @protected
  MessageUpdate dco_decode_message_update(dynamic raw);

  @protected
  MessageWithTokens dco_decode_message_with_tokens(dynamic raw);

  @protected
  NotificationTrigger dco_decode_notification_trigger(dynamic raw);

  @protected
  NotificationUpdate dco_decode_notification_update(dynamic raw);

  @protected
  NotificationUser dco_decode_notification_user(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ChatMessageSummary? dco_decode_opt_box_autoadd_chat_message_summary(
    dynamic raw,
  );

  @protected
  DeliveryStatus? dco_decode_opt_box_autoadd_delivery_status(dynamic raw);

  @protected
  Draft? dco_decode_opt_box_autoadd_draft(dynamic raw);

  @protected
  FileMetadata? dco_decode_opt_box_autoadd_file_metadata(dynamic raw);

  @protected
  FlutterEvent? dco_decode_opt_box_autoadd_flutter_event(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  List<Tag>?
  dco_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  U8Array12? dco_decode_opt_u_8_array_12(dynamic raw);

  @protected
  U8Array32? dco_decode_opt_u_8_array_32(dynamic raw);

  @protected
  RatchetTreeInfo dco_decode_ratchet_tree_info(dynamic raw);

  @protected
  ReactionSummary dco_decode_reaction_summary(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  Relay dco_decode_relay(dynamic raw);

  @protected
  SearchUpdateTrigger dco_decode_search_update_trigger(dynamic raw);

  @protected
  SerializableToken dco_decode_serializable_token(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array12 dco_decode_u_8_array_12(dynamic raw);

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateTrigger dco_decode_update_trigger(dynamic raw);

  @protected
  UploadGroupImageResult dco_decode_upload_group_image_result(dynamic raw);

  @protected
  User dco_decode_user(dynamic raw);

  @protected
  UserReaction dco_decode_user_reaction(dynamic raw);

  @protected
  UserSearchResult dco_decode_user_search_result(dynamic raw);

  @protected
  UserSearchUpdate dco_decode_user_search_update(dynamic raw);

  @protected
  UserStreamItem dco_decode_user_stream_item(dynamic raw);

  @protected
  UserUpdate dco_decode_user_update(dynamic raw);

  @protected
  UserUpdateTrigger dco_decode_user_update_trigger(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WhitenoiseConfig dco_decode_whitenoise_config(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AppSettings
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    SseDeserializer deserializer,
  );

  @protected
  DartSigner
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    SseDeserializer deserializer,
  );

  @protected
  GroupId
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    SseDeserializer deserializer,
  );

  @protected
  Language
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    SseDeserializer deserializer,
  );

  @protected
  PublicKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    SseDeserializer deserializer,
  );

  @protected
  RelayType
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    SseDeserializer deserializer,
  );

  @protected
  RelayUrl
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    SseDeserializer deserializer,
  );

  @protected
  Tag
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    SseDeserializer deserializer,
  );

  @protected
  ThemeMode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    SseDeserializer deserializer,
  );

  @protected
  AppSettings
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    SseDeserializer deserializer,
  );

  @protected
  GroupId
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    SseDeserializer deserializer,
  );

  @protected
  Language
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    SseDeserializer deserializer,
  );

  @protected
  RelayUrl
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    SseDeserializer deserializer,
  );

  @protected
  ThemeMode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    SseDeserializer deserializer,
  );

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  AppSettings
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    SseDeserializer deserializer,
  );

  @protected
  DartSigner
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    SseDeserializer deserializer,
  );

  @protected
  GroupId
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    SseDeserializer deserializer,
  );

  @protected
  Language
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    SseDeserializer deserializer,
  );

  @protected
  PublicKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    SseDeserializer deserializer,
  );

  @protected
  RelayType
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    SseDeserializer deserializer,
  );

  @protected
  RelayUrl
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    SseDeserializer deserializer,
  );

  @protected
  Tag
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    SseDeserializer deserializer,
  );

  @protected
  ThemeMode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ChatListStreamItem>
  sse_decode_StreamSink_chat_list_stream_item_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<MessageStreamItem>
  sse_decode_StreamSink_message_stream_item_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<NotificationUpdate>
  sse_decode_StreamSink_notification_update_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<UserSearchUpdate> sse_decode_StreamSink_user_search_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UserStreamItem> sse_decode_StreamSink_user_stream_item_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Account sse_decode_account(SseDeserializer deserializer);

  @protected
  AccountGroup sse_decode_account_group(SseDeserializer deserializer);

  @protected
  AccountType sse_decode_account_type(SseDeserializer deserializer);

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ApiError sse_decode_box_autoadd_api_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChatListUpdate sse_decode_box_autoadd_chat_list_update(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessageSummary sse_decode_box_autoadd_chat_message_summary(
    SseDeserializer deserializer,
  );

  @protected
  DeliveryStatus sse_decode_box_autoadd_delivery_status(
    SseDeserializer deserializer,
  );

  @protected
  Draft sse_decode_box_autoadd_draft(SseDeserializer deserializer);

  @protected
  FileMetadata sse_decode_box_autoadd_file_metadata(
    SseDeserializer deserializer,
  );

  @protected
  FlutterEvent sse_decode_box_autoadd_flutter_event(
    SseDeserializer deserializer,
  );

  @protected
  FlutterGroupDataUpdate sse_decode_box_autoadd_flutter_group_data_update(
    SseDeserializer deserializer,
  );

  @protected
  FlutterMetadata sse_decode_box_autoadd_flutter_metadata(
    SseDeserializer deserializer,
  );

  @protected
  Group sse_decode_box_autoadd_group(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MessageUpdate sse_decode_box_autoadd_message_update(
    SseDeserializer deserializer,
  );

  @protected
  User sse_decode_box_autoadd_user(SseDeserializer deserializer);

  @protected
  UserUpdate sse_decode_box_autoadd_user_update(SseDeserializer deserializer);

  @protected
  WhitenoiseConfig sse_decode_box_autoadd_whitenoise_config(
    SseDeserializer deserializer,
  );

  @protected
  ChatListStreamItem sse_decode_chat_list_stream_item(
    SseDeserializer deserializer,
  );

  @protected
  ChatListUpdate sse_decode_chat_list_update(SseDeserializer deserializer);

  @protected
  ChatListUpdateTrigger sse_decode_chat_list_update_trigger(
    SseDeserializer deserializer,
  );

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer);

  @protected
  ChatMessageSummary sse_decode_chat_message_summary(
    SseDeserializer deserializer,
  );

  @protected
  ChatSummary sse_decode_chat_summary(SseDeserializer deserializer);

  @protected
  DeliveryStatus sse_decode_delivery_status(SseDeserializer deserializer);

  @protected
  Draft sse_decode_draft(SseDeserializer deserializer);

  @protected
  EmojiReaction sse_decode_emoji_reaction(SseDeserializer deserializer);

  @protected
  FileMetadata sse_decode_file_metadata(SseDeserializer deserializer);

  @protected
  FlutterEvent sse_decode_flutter_event(SseDeserializer deserializer);

  @protected
  FlutterGroupDataUpdate sse_decode_flutter_group_data_update(
    SseDeserializer deserializer,
  );

  @protected
  FlutterMetadata sse_decode_flutter_metadata(SseDeserializer deserializer);

  @protected
  Group sse_decode_group(SseDeserializer deserializer);

  @protected
  GroupInformation sse_decode_group_information(SseDeserializer deserializer);

  @protected
  GroupState sse_decode_group_state(SseDeserializer deserializer);

  @protected
  GroupType sse_decode_group_type(SseDeserializer deserializer);

  @protected
  GroupWithInfoAndMembership sse_decode_group_with_info_and_membership(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  KeyPackageStatus sse_decode_key_package_status(SseDeserializer deserializer);

  @protected
  LeafNodeInfo sse_decode_leaf_node_info(SseDeserializer deserializer);

  @protected
  List<Tag>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Account> sse_decode_list_account(SseDeserializer deserializer);

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer);

  @protected
  List<ChatSummary> sse_decode_list_chat_summary(SseDeserializer deserializer);

  @protected
  List<EmojiReaction> sse_decode_list_emoji_reaction(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterEvent> sse_decode_list_flutter_event(
    SseDeserializer deserializer,
  );

  @protected
  List<Group> sse_decode_list_group(SseDeserializer deserializer);

  @protected
  List<GroupInformation> sse_decode_list_group_information(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupWithInfoAndMembership>
  sse_decode_list_group_with_info_and_membership(SseDeserializer deserializer);

  @protected
  List<LeafNodeInfo> sse_decode_list_leaf_node_info(
    SseDeserializer deserializer,
  );

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<MatchedField> sse_decode_list_matched_field(
    SseDeserializer deserializer,
  );

  @protected
  List<MediaFile> sse_decode_list_media_file(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<Relay> sse_decode_list_relay(SseDeserializer deserializer);

  @protected
  List<SerializableToken> sse_decode_list_serializable_token(
    SseDeserializer deserializer,
  );

  @protected
  List<User> sse_decode_list_user(SseDeserializer deserializer);

  @protected
  List<UserReaction> sse_decode_list_user_reaction(
    SseDeserializer deserializer,
  );

  @protected
  List<UserSearchResult> sse_decode_list_user_search_result(
    SseDeserializer deserializer,
  );

  @protected
  LoginResult sse_decode_login_result(SseDeserializer deserializer);

  @protected
  LoginStatus sse_decode_login_status(SseDeserializer deserializer);

  @protected
  MatchQuality sse_decode_match_quality(SseDeserializer deserializer);

  @protected
  MatchedField sse_decode_matched_field(SseDeserializer deserializer);

  @protected
  MediaFile sse_decode_media_file(SseDeserializer deserializer);

  @protected
  MessageStreamItem sse_decode_message_stream_item(
    SseDeserializer deserializer,
  );

  @protected
  MessageUpdate sse_decode_message_update(SseDeserializer deserializer);

  @protected
  MessageWithTokens sse_decode_message_with_tokens(
    SseDeserializer deserializer,
  );

  @protected
  NotificationTrigger sse_decode_notification_trigger(
    SseDeserializer deserializer,
  );

  @protected
  NotificationUpdate sse_decode_notification_update(
    SseDeserializer deserializer,
  );

  @protected
  NotificationUser sse_decode_notification_user(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChatMessageSummary? sse_decode_opt_box_autoadd_chat_message_summary(
    SseDeserializer deserializer,
  );

  @protected
  DeliveryStatus? sse_decode_opt_box_autoadd_delivery_status(
    SseDeserializer deserializer,
  );

  @protected
  Draft? sse_decode_opt_box_autoadd_draft(SseDeserializer deserializer);

  @protected
  FileMetadata? sse_decode_opt_box_autoadd_file_metadata(
    SseDeserializer deserializer,
  );

  @protected
  FlutterEvent? sse_decode_opt_box_autoadd_flutter_event(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  List<Tag>?
  sse_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  U8Array12? sse_decode_opt_u_8_array_12(SseDeserializer deserializer);

  @protected
  U8Array32? sse_decode_opt_u_8_array_32(SseDeserializer deserializer);

  @protected
  RatchetTreeInfo sse_decode_ratchet_tree_info(SseDeserializer deserializer);

  @protected
  ReactionSummary sse_decode_reaction_summary(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  Relay sse_decode_relay(SseDeserializer deserializer);

  @protected
  SearchUpdateTrigger sse_decode_search_update_trigger(
    SseDeserializer deserializer,
  );

  @protected
  SerializableToken sse_decode_serializable_token(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array12 sse_decode_u_8_array_12(SseDeserializer deserializer);

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateTrigger sse_decode_update_trigger(SseDeserializer deserializer);

  @protected
  UploadGroupImageResult sse_decode_upload_group_image_result(
    SseDeserializer deserializer,
  );

  @protected
  User sse_decode_user(SseDeserializer deserializer);

  @protected
  UserReaction sse_decode_user_reaction(SseDeserializer deserializer);

  @protected
  UserSearchResult sse_decode_user_search_result(SseDeserializer deserializer);

  @protected
  UserSearchUpdate sse_decode_user_search_update(SseDeserializer deserializer);

  @protected
  UserStreamItem sse_decode_user_stream_item(SseDeserializer deserializer);

  @protected
  UserUpdate sse_decode_user_update(SseDeserializer deserializer);

  @protected
  UserUpdateTrigger sse_decode_user_update_trigger(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WhitenoiseConfig sse_decode_whitenoise_config(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    DartSigner self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    GroupId self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    Language self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    PublicKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    RelayType self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    RelayUrl self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    Tag self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    ThemeMode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    GroupId self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    Language self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    RelayUrl self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    ThemeMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_String_Output_String_AnyhowException(
    FutureOr<String> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_String_Output_String_AnyhowException(
    FutureOr<String> Function(String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    DartSigner self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    GroupId self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    Language self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    PublicKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    RelayType self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    RelayUrl self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    Tag self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    ThemeMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_chat_list_stream_item_Sse(
    RustStreamSink<ChatListStreamItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_message_stream_item_Sse(
    RustStreamSink<MessageStreamItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_notification_update_Sse(
    RustStreamSink<NotificationUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_user_search_update_Sse(
    RustStreamSink<UserSearchUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_user_stream_item_Sse(
    RustStreamSink<UserStreamItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_account_group(AccountGroup self, SseSerializer serializer);

  @protected
  void sse_encode_account_type(AccountType self, SseSerializer serializer);

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(
    DateTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_error(
    ApiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chat_list_update(
    ChatListUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_chat_message_summary(
    ChatMessageSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delivery_status(
    DeliveryStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_draft(Draft self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_file_metadata(
    FileMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_event(
    FlutterEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_group_data_update(
    FlutterGroupDataUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_metadata(
    FlutterMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group(Group self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_update(
    MessageUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_update(
    UserUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_whitenoise_config(
    WhitenoiseConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_list_stream_item(
    ChatListStreamItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_list_update(
    ChatListUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_list_update_trigger(
    ChatListUpdateTrigger self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_chat_message_summary(
    ChatMessageSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_summary(ChatSummary self, SseSerializer serializer);

  @protected
  void sse_encode_delivery_status(
    DeliveryStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_draft(Draft self, SseSerializer serializer);

  @protected
  void sse_encode_emoji_reaction(EmojiReaction self, SseSerializer serializer);

  @protected
  void sse_encode_file_metadata(FileMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_event(FlutterEvent self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_group_data_update(
    FlutterGroupDataUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_metadata(
    FlutterMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group(Group self, SseSerializer serializer);

  @protected
  void sse_encode_group_information(
    GroupInformation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_state(GroupState self, SseSerializer serializer);

  @protected
  void sse_encode_group_type(GroupType self, SseSerializer serializer);

  @protected
  void sse_encode_group_with_info_and_membership(
    GroupWithInfoAndMembership self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_package_status(
    KeyPackageStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_leaf_node_info(LeafNodeInfo self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    List<Tag> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account(List<Account> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chat_summary(
    List<ChatSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_emoji_reaction(
    List<EmojiReaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_event(
    List<FlutterEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group(List<Group> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group_information(
    List<GroupInformation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_with_info_and_membership(
    List<GroupWithInfoAndMembership> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_leaf_node_info(
    List<LeafNodeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_matched_field(
    List<MatchedField> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_file(
    List<MediaFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relay(List<Relay> self, SseSerializer serializer);

  @protected
  void sse_encode_list_serializable_token(
    List<SerializableToken> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user(List<User> self, SseSerializer serializer);

  @protected
  void sse_encode_list_user_reaction(
    List<UserReaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_search_result(
    List<UserSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_result(LoginResult self, SseSerializer serializer);

  @protected
  void sse_encode_login_status(LoginStatus self, SseSerializer serializer);

  @protected
  void sse_encode_match_quality(MatchQuality self, SseSerializer serializer);

  @protected
  void sse_encode_matched_field(MatchedField self, SseSerializer serializer);

  @protected
  void sse_encode_media_file(MediaFile self, SseSerializer serializer);

  @protected
  void sse_encode_message_stream_item(
    MessageStreamItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_update(MessageUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_message_with_tokens(
    MessageWithTokens self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_trigger(
    NotificationTrigger self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_update(
    NotificationUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_user(
    NotificationUser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(
    DateTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_chat_message_summary(
    ChatMessageSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_delivery_status(
    DeliveryStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_draft(Draft? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_file_metadata(
    FileMetadata? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_flutter_event(
    FlutterEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    List<Tag>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_u_8_array_12(U8Array12? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_u_8_array_32(U8Array32? self, SseSerializer serializer);

  @protected
  void sse_encode_ratchet_tree_info(
    RatchetTreeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reaction_summary(
    ReactionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relay(Relay self, SseSerializer serializer);

  @protected
  void sse_encode_search_update_trigger(
    SearchUpdateTrigger self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_serializable_token(
    SerializableToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_12(U8Array12 self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_trigger(UpdateTrigger self, SseSerializer serializer);

  @protected
  void sse_encode_upload_group_image_result(
    UploadGroupImageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_user_reaction(UserReaction self, SseSerializer serializer);

  @protected
  void sse_encode_user_search_result(
    UserSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_search_update(
    UserSearchUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_stream_item(
    UserStreamItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_update(UserUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_user_update_trigger(
    UserUpdateTrigger self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_whitenoise_config(
    WhitenoiseConfig self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettingsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettingsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettingsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettings =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppSettingsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSignerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSignerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSignerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSigner =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartSignerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupIdPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupIdPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupIdPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupId =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGroupIdPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguagePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguage =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLanguagePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKey =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPublicKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayTypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayTypePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayTypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayType =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayTypePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrlPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrlPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrlPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrl =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRelayUrlPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTagPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTagPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTagPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTag =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTagPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeModePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeModePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeModePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_whitenoise_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeMode =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThemeModePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
