// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

// These functions are ignored because they are not marked as `pub`: `rust_log_path`

/// Stream new lines from the Rust log file to Flutter.
/// Tails the whitenoise log file and emits each new line via the sink.
Stream<String> subscribeToRustLogs({required String logsBaseDir}) => RustLib
    .instance
    .api
    .crateApiLogsSubscribeToRustLogs(logsBaseDir: logsBaseDir);
