// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Stream<NotificationUpdate> subscribeToNotifications() =>
    RustLib.instance.api.crateApiNotificationsSubscribeToNotifications();

enum NotificationTrigger {
  newMessage,
  groupInvite,
}

class NotificationUpdate {
  final NotificationTrigger trigger;
  final String mlsGroupId;
  final String? groupName;
  final bool isDm;
  final NotificationUser receiver;
  final NotificationUser sender;
  final String content;
  final DateTime timestamp;

  const NotificationUpdate({
    required this.trigger,
    required this.mlsGroupId,
    this.groupName,
    required this.isDm,
    required this.receiver,
    required this.sender,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      trigger.hashCode ^
      mlsGroupId.hashCode ^
      groupName.hashCode ^
      isDm.hashCode ^
      receiver.hashCode ^
      sender.hashCode ^
      content.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationUpdate &&
          runtimeType == other.runtimeType &&
          trigger == other.trigger &&
          mlsGroupId == other.mlsGroupId &&
          groupName == other.groupName &&
          isDm == other.isDm &&
          receiver == other.receiver &&
          sender == other.sender &&
          content == other.content &&
          timestamp == other.timestamp;
}

class NotificationUser {
  final String pubkey;
  final String? displayName;
  final String? pictureUrl;

  const NotificationUser({
    required this.pubkey,
    this.displayName,
    this.pictureUrl,
  });

  @override
  int get hashCode =>
      pubkey.hashCode ^ displayName.hashCode ^ pictureUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationUser &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          displayName == other.displayName &&
          pictureUrl == other.pictureUrl;
}
